### ISSUE TITLE
Implement compatibility checks between munlib and runtime

### ISSUE THREAD

**Issue by baszalmstra** [mun-lang/mun#188]
**Problem**

Currently, the runtime tries to load a `*.munlib` with the assumption that the ABI memory layout of the `*.munlib` matches its own ABI version. This can cause undefined behaviour when it tries to load a `*.munlib` with a different ABI version.

**Solution**

By including an ABI version in the `*.munlib`, the runtime can gracefully fail - reporting an error to the end user.

In the future - once we support backwards compatibility, we can even support loading of several different ABI versions using this functionality.

**Tasks**

- [ ] add an integer `ABI_VERSION` constant to the `mun_abi` crate.
- [ ] [generate](https://github.com/mun-lang/mun/blob/0d6e36d64376289a8969c62cefdc080ee99c2a51/crates/mun_codegen/src/code_gen/symbols.rs#L291) a `get_version` IR function
- [ ] [export](https://github.com/mun-lang/mun/blob/c17448d77f9751e74ce90ea49cd8503b35459d8e/crates/mun_codegen/src/code_gen/linker.rs#L176) the `get_version` function
- [ ] in the [runtime](https://github.com/mun-lang/mun/blob/master/crates/mun_runtime/src/assembly.rs#L35), call the `get_version` function and verify that the runtime's `mun_abi::ABI_VERSION` is compatible.
- [ ] (bonus) add a constant with the `get_version` function name (and other API functions) to the `mun_abi` crate and use that constant in both the `mun_codegen` and `mun_runtime` crates - to avoid discrepancies.

**Good first issue process:**

- [ ] [read our contributing guidelines](https://github.com/mun-lang/mun/blob/master/CONTRIBUTING.md)
- [ ] claim this issue (assign yourself or comment below)
- [ ] implement the feature and start a Pull Request with in the description: closes #188. 

If this is your first PR, welcome 🎉 😄

**Comment by MineBill** [comment]
I would like to tackle this issue and implement the feature. This will be my first ever PR.

**Comment by Wodann** [comment]
Welcome and thank you for working on this PR. If you have any questions, please let us know.

**Comment by MineBill** [comment]
After implementing this,  the following tests fail:
```
tests::abi_is_fresh
tests::runtime_capi_is_fresh
```
They require me to update the abi and the runtime-capi but doing so requires me to download both the [ffi](https://github.com/mun-lang/runtime-ffi/tree/ac61e99025ece3a8105bf95a7a1ff70506f74bd3) and the [abi-c](https://github.com/mun-lang/abi-c/tree/4bccc48f4c782fa06c1ae911b2f7bf36e587280c) submodules. What should i do?

**Comment by Wodann** [comment]
You should always download the submodules, otherwise the tests will fail. Our install instructions describe how to do it. It's a single command:
```bash
git submodule update --init --recursive
```

**Comment by Wodann** [comment]
Exemplary work! Really quick workflow from claiming the issue, to submitting a PR, and incorporating recommended changes. Well done 👍
