### ISSUE TITLE
Garbage Collection

### ISSUE THREAD

**Issue by Wodann** [mun-lang/mun#206]
Currently, the Mun runtime defaults to a mark & sweep garbage collector (henceforth GC). This a relatively simple implementation of a GC, that serves as a good proof of concept. However, going foreword we need to mature our GC story.

**Goals**

1. [ ] **Benchmarking** - The first step should be to create a benchmark suite that is used to avoid regression and guides high-level optimisations.
  ![image](https://user-images.githubusercontent.com/6917585/82874323-10f89b80-9f36-11ea-85e1-82989faa17e5.png)
  **[discussion A]** What metrics/use cases are important to benchmark?
2. [ ] **Constantly low overhead** The Mun GC will have to run at interactive frame rate (30-60 Hz). As such it only has a minimal time budget to spend on GC - every frame.
3. [ ] **Rewrite the stack** As Mun hot reloads state, data structures have to be mapped in memory. The current Mun GC is limited to rewriting all GC-allocated memory, but in the future we also want it to rewrite stack memory.
4. [ ] **Concurrency** In the future, we want to implement some form of concurrency within the Mun runtime. As such, GC design discussions should sync up with Mun concurrency design discussions.

**Comment by Wodann** [comment]
Minutes from a Discord discussion on GC:

- Concurrent, tracing GC
  - [cgc](https://crates.io/crates/cgc) is a really simple implementation of a concurrent, copying GC that generalises over types.
    - Mun cannot directly adopt `cgc` as it operates on byte-memory, similar to the `alloc` API.
  - [Riptide](https://webkit.org/blog/7122/introducing-riptide-webkits-retreating-wavefront-concurrent-garbage-collector) is a relatively simple, concurrent, non-copying GC
    - Even though the current Mun GC is non-copying, Mun will likely have to support some form of barriers (or state points) in the future, so we can also investigate copying GCs.
  - [JVM GC](https://www.youtube.com/watch?v=VCeHkcwfF9Q) is another option
    - JVM's implementation of [safepoints](http://blog.ragozin.info/2012/10/safepoints-in-hotspot-jvm.html) cleverly uses function calls (an optimisation over a memory read)
- Shenandoah is a low-pause GC that uses barriers ([video](https://www.youtube.com/watch?v=VCeHkcwfF9Q), [wiki](https://wiki.openjdk.java.net/display/shenandoah/Main), [paper](https://www.researchgate.net/publication/306112816_Shenandoah_An_open-source_concurrent_compacting_garbage_collector_for_OpenJDK)
- [LLVM GC](https://www.llvm.org/docs/GarbageCollection.html) might be an interesting option for Mun
  - It seems like no one in the [proglangdev](https://proglangdesign.net) [Discord](https://discord.gg/4Kjt3ZE) is using the LLVM GC API
- Stack scanning
  - Conceptually, we can use LLVM to do stack scanning
  - `scala-native` uses a conservative scanning approach:
    ```rust
    scan = stack_top;
    while scan < stack_end {
      if heap.contains_ptr(scan) {...}
      scan = scan.offset(mem::size_of::<*const c_void>());
    }
    ```
  - You can combine a copying GC with conservative root scanning, if you:
    1. allocate 16kb blocks - for pointer alignment;
    2. check whether a heap contains a pointer as follows:
      ```rust
      fn has_pointer(&self, ptr: *const u8) -> bool {
        let block_ptr = ptr & BLOCK_MASK;
        for block in self.blocks.iter() {
          if block.header == block_ptr {
             return true;
          }    
        }
        false
      }
      ```
    3. tag integers and floats - to prevent numbers from being mistaken for pointers - or allocate them on the heap
  - A caveat of programming in a (tracing) GC'd language can get awkward as you try to avoid generating garbage
- Reference-counted GC
  - [Swift](https://swift.org)
  - [Python](python.org) uses cycle detection/elimination
  - [Immix reference counting](https://www.microsoft.com/en-us/research/publication/taking-off-the-gloves-with-reference-counting-immix) approaches performance of the best tracing GCs
    - The [immix-rust](https://github.com/raviqqe/immix-rust) implementation might be a good starting point for experimentation. There has been some prior discussion on [Reddit](https://www.reddit.com/r/rust/comments/awx9cy/github_kyrenluster_an_experimental_lua_vm/ehqki10/)
- Static memory management
  - Lifetime system (like Rust)
  - [micro-mitten](https://github.com/doctorn/micro-mitten) uses static data-flow analysis to approximate heap liveness.
  - A potential caveat that was named is Mun needing a type memory map of all heap allocations, but it's completely possible to still maintain such a memory map when not using a GC.

**Comment by baszalmstra** [comment]
Note that immix-rust is not a _reference-counting_ GC

**Comment by atennapel** [comment]
Also see [Counting Immutable Beans](https://arxiv.org/abs/1908.05647) for an implementation of reference counting in the Lean theorem prover. They do some clever things like reusing data structures if the reference count is 1.

**Comment by pitaj** [comment]
I'd just like to point out the option of a colored-pointer GC like ZGC. While ZGC only works on 64-bit architectures (because it needs the extra bits for colored pointers), it has very short pause times that do not scale directly with heap size.

**Comment by YorickPeterse** [comment]
If I remember correctly, the immix-rust repository does not implement everything of Immix. Specifically, it does not support compacting the heap if my memory serves me right. For [Inko](https://inko-lang.org) I ended up implementing in Immix, including support for compacting the heap. If it's of any use, you can find the code for it here:

* https://gitlab.com/inko-lang/inko/-/tree/master/vm/src/gc: code for tracing heaps and what not
* https://gitlab.com/inko-lang/inko/-/tree/master/vm/src/immix: code for the allocator, and a bunch of helper code/structures

I'm happy to answer any questions about Immix as well :smiley:

**Comment by moon-chilled** [comment]
@pitaj you can use coloured-pointer gcs on 32-bit platforms if you use the low-order bits for colouring; for example, zgc currently uses only 4 bits for colouring, so if you align every allocation to 16 bytes, the low 4 bits are irrelevant.  The downside is that you have to mask every pointer reference (gc can't clean up after itself if it runs concurrently), so it may not be a worthwhile tradeoff.

**Comment by playXE** [comment]
I'll try to make GC API more generic in: [Issue 207](https://github.com/mun-lang/mun/issues/207) and soon create PR with initial changes to API.

**Comment by steveblackburn** [comment]
Lots of interesting thoughts above.

We're doing a full re-write of [MMTk](https://github.com/JikesRVM/JikesRVM/tree/master/MMTk) in Rust.     Although our implementation is not yet public (I hope to have it for you soon), you can take a browse at the Java code base on which the Rust re-write is based.    They key difference is that the re-write targets multiple VMs and multiple languages.

**Comment by AlexCouch** [comment]
I haven't seen Conservative GC be mentioned yet which is what Crystal uses for GC so I'm gonna leave a link here to both:
[Conservative GC](https://hboehm.info/gc/conservative.html)
[Crystal-lang](https://github.com/crystal-lang/crystal)

**Comment by fleabitdev** [comment]
Hi folks,

I was pointed to this issue by @erlend-sh, after announcing [GameLisp](https://gamelisp.rs/) yesterday.

You might be interested by GameLisp's garbage collector. It's not an exact fit for Mun (because Mun seems to be a much more general-purpose language than GameLisp), but you might be able to borrow some ideas. There's a guide-level explanation [here](https://gamelisp.rs/reference/garbage-collection.html), some basic performance figures [here](https://gamelisp.rs/reference/performance-figures.html#specimen-project), a detailed technical overview [here](https://github.com/fleabitdev/glsp/blob/master/notes/gc.md), and the source code itself is [here](https://github.com/fleabitdev/glsp/blob/master/glsp-engine/src/gc.rs).

Technical summary:

- The GC is invoked explicitly once per frame, rather than waiting for a memory allocation.
- It's generational, which immediately trivializes 90%+ of the garbage generated by a typical game.
- It's incremental, scaling the amount of work done to the amount of memory allocated since the GC was last invoked. The algorithm contains a few clever tricks to prevent latency spikes, at the cost of increased total memory usage and a more expensive write-barrier.
- The GC can optionally be implemented without using any `unsafe` code, by abusing `std::rc::Rc`.

One of the most surprising things I learned while implementing the GC is that, for games, the raw throughput of the garbage collector just doesn't matter very much. GameLisp's algorithm has a lot of room for optimization (especially if I were willing to make heavier use of `unsafe` code), but even now, the ratio of script-execution time to GC time is something like 20:1. Because most games are unlikely to spend more than a few milliseconds each frame executing scripts, the cost of the GC is negligible.

Let me know if you have any questions!

**Comment by erlend-sh** [comment]
Might Dart’s GC be a useful reference for Mun? The two languages seem to have pretty similar design goals. Dart uses a generational GC, like GameLisp.

https://medium.com/flutter/flutter-dont-fear-the-garbage-collector-d69b3ff1ca30

**Comment by Techcable** [comment]
Consider looking into the [Memory Pool System](https://www.ravenbrook.com/project/mps/).

It implements a generational GC with bump-pointer allocation.

Language integration is *much* easier than with MMTK (having tried both). 

Although the library is not very widely known, it is backed by a professional contracting-firm. It is used in production in multiple language implementations (main one is OpenDylan).

This project might be worth taking a look at. In addition to bump-pointer allocation and generational collection, it also supports concurrent collection! It is likely to be faster than whatever you can write yourself (unless you put like a *ton* of effort in it).

It is not quite as fast level of MMTK/Java/Go, but can be surprisingly competitive 😄 

If you do decide to write a collector yourself, "The Garbage Collection Handbook" is very useful (and exceptionally well written).

**Downsides on MPS**:
Write barriers are done using OS-level page protection. While this makes compilation easier, this means that some of your callback functions might be called from inside signal handlers.

Also collection is (mostly) concurrent, so your trace functions might be called from other threads (and collections can happen any time, not just at allocations).

Because of these two things, Integration is difficult to do unless its in C. The library uses a lot of macro magic. Signal handlers can be tricky to get right in higher-level languages (even Rust) while the macros take care of it in C.

Inline allocation is an exception, and is easy to do even in hand-written/JIT compiled assembly.

**Comment by baszalmstra** [comment]
Very interesting read!

**Comment by steveblackburn** [comment]
@Techcable I'm keen to hear of your MMTk experience.   What language were you porting?   Any thoughts on what you found difficult?

We have a lively community with a lot of ports underway right now, and some pretty interesting work with new algorithms (outperforming G1 and Shenandoah on OpenJDK now).

**Comment by typesanitizer** [comment]
@erlend-sh I called off the study because I didn't get much initial interest (only a handful of survey responses) to be able to perform a meaningful study. 😐
