### ISSUE TITLE
WebAssembly support

### ISSUE THREAD

**Issue by Wodann** [mun-lang/mun#215]
Web creators being one of our target audiences, we set the goal:
> Use the same Mun toolchain to build, test, and deploy content to the web using WebAssembly modules.

What is needed to achieve this goal?

- [ ] Compile the `mun_runtime` for the wasm target
- [ ] Test runtime-linking of `*.munlib` files in the browser
     - [ ] If impossible, add `mun_compiler` support for compiling LLVM IR to WebAssembly byte code - instead of machine code

**Comment by mamidon** [comment]
I take it compiling to webassembly is a goal, but not yet implemented?

**Comment by Wodann** [comment]
> I take it compiling to webassembly is a goal, but not yet implemented?

That's correct. Our next steps are outlined in the top-level post.
