### ISSUE TITLE
Game console support

### ISSUE THREAD

**Issue by Wodann** [mun-lang/mun#219]
Game console developers being one of our target audiences, we set the goal:
> Leverage Mun's cross compilation to unlock hot reloading for console and mobile development.

**Currently, game consoles are not part of Mun's supported target platforms.**

The first steps towards achieving this goal, would be:
- [ ] (optional) Investigate Rust compilation on game consoles.
- [ ] (optional) Investigate compilation of and linking to `mun_runtime` for game console-supported targets

*Alternatively*, use the `mun_runtime` shared library and C/C++ bindings
- [ ] Investigate opening of shared libraries (needed for `*.munlib`s) with the respective game console operating system
